name: elkitap
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+2

environment:
  sdk: ">=3.6.0 <4.0.0"



dependencies:
  flutter:
    sdk: flutter


  
  #==================== FIREBASE ====================#
  firebase_core: ^3.1.1
  firebase_core_platform_interface: ^6.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^18.0.1
  firebase_performance: ^0.10.1+10
  

  #==================== STATE MANAGEMENT ====================#
  get: ^4.6.6



  #==================== NETWORK ====================#
  http:
  dio: ^5.3.3


  #==================== UI & UX ====================#
  flutter_screenutil: ^5.9.3
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  lottie: ^3.3.0
  upgrader: ^10.3.0
  flutter_html: ^3.0.0-beta.2
  flutter_svg: ^2.0.12
  video_player: ^2.10.0
  
  # flutter_epub_viewer: ^1.2.2
  path_provider: ^2.1.5
  just_audio: ^0.10.5
  pinput: ^5.0.1
  
  # isar_flutter_libs: ^3.1.0+1
  cosmos_epub:
    path: ./packages/cosmos_epub
  # vocsy_epub_viewer: ^3.0.0

  #==================== MAPS & LOCATION ====================#
  permission_handler: ^11.0.1
  

  #==================== LOCAL STORAGE ====================#
  get_storage: ^2.1.1

  #==================== UTILITIES ====================#
  
  intl: ^0.20.2
  url_launcher: ^6.2.1
  sms_autofill: ^2.4.1

  #==================== MEDIA ====================#
  photo_view: ^0.15.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  just_audio_background: ^0.0.1-beta.17
  audio_service: ^0.18.18
  


dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^5.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/videos/
    - assets/books/
    - assets/audio/
    - assets/splash.json
    
   


  fonts:
    - family: SFPro
      fonts:
        - asset: assets/fonts/SF-Pro.ttf
       


    - family: NewYork
      fonts:
        - asset: assets/fonts/NewYork.ttf
       
    - family: NewYorkItalic
      fonts:
        - asset: assets/fonts/NewYorkItalic.ttf    
          
 
